import Image from "next/image";

export default function SkillForntend() {
  return (
    <div className="mb-6 pb-6 border-b flex gap-10 items-center flex-wrap">
      <Image
        src="/skills/html5.svg"
        width={60}
        height={60}
        alt="html아이콘"
        title="html5"
      />
      <Image
        src="/skills/css3.svg"
        width={43}
        height={43}
        alt="css아이콘"
        title="css3"
      />
      <Image
        src="/skills/javascript.svg"
        width={60}
        height={60}
        alt="JS아이콘"
        title="JavaScript"
      />
      <Image
        src="/skills/typescript.svg"
        width={60}
        height={60}
        alt="TS아이콘"
        title="TypeScript"
      />
      <Image
        src="/skills/react.svg"
        width={60}
        height={60}
        alt="react아이콘"
        title="React"
      />
      <Image
        src="/skills/nextjs.svg"
        width={100}
        height={60}
        alt="nextjs아이콘"
        title="Next.js"
      />
      <Image
        src="/skills/styled-components.svg"
        width={60}
        height={60}
        alt="styled-components아이콘"
        title="Styled-Components"
      />
      <Image
        src="/skills/tailwind.svg"
        width={60}
        height={60}
        alt="tailwind아이콘"
        title="tailwindCSS"
      />
      <Image
        src="/skills/zustand.png"
        width={80}
        height={80}
        alt="zustand아이콘"
        title="zustand"
      />
      <Image
        src="/skills/vite.svg"
        width={60}
        height={60}
        alt="vite아이콘"
        title="vite"
      />
      <Image
        src="/skills/axios.png"
        width={80}
        height={80}
        alt="axios아이콘"
        title="axios"
      />
    </div>
  );
}
